# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 989bc1f7b537d9140c630b582146b228c02c0495ef55ad99ef5349b51112e45e615e127664489bdcec7f9406f567724e6e101b63074fb87bd6d9d41bac63dba1

test:
  secret_key_base: 9d1969958f1e07f17751339963ee74cb3cebbbeccb17901f7dc1fb83e61887f09fa13336711b5e1f2ef68b44b2e107e7e670b770c25cd7cb2aa71610c53bf9cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
